import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { z } from "astro/zod";
import { format } from "prettier";

import {
  blogFrontmatterDate,
  createBlogFrontmatterSchema,
} from "../src/content/blog-schema.ts";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const schemaPath = join(repoRoot, "schemas", "blog-frontmatter.schema.json");

/** Builds the JSON Schema object for blog post frontmatter. */
export function blogFrontmatterJsonSchema(): Record<string, unknown> {
  const frontmatterSchema = createBlogFrontmatterSchema({
    date: blogFrontmatterDate,
    image: () =>
      z
        .string()
        .min(1)
        .describe("Local relative path or supported remote HTTPS image."),
  });

  const { $schema, ...jsonSchema } = z.toJSONSchema(frontmatterSchema, {
    io: "input",
  });

  return {
    $schema,
    $id: "https://jimeh.me/schemas/blog-frontmatter.schema.json",
    title: "jimeh.me Blog Frontmatter",
    description: "Frontmatter schema for posts in src/content/blog.",
    $comment:
      "Generated by scripts/generate-blog-frontmatter-schema.ts; do not edit.",
    ...jsonSchema,
  };
}

/** Writes the formatted blog frontmatter JSON Schema file. */
export async function generateBlogFrontmatterSchema(
  outputPath = schemaPath,
): Promise<void> {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(
    outputPath,
    await format(JSON.stringify(blogFrontmatterJsonSchema(), null, 2), {
      parser: "json",
    }),
  );
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  await generateBlogFrontmatterSchema();
}
