import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { z } from "astro/zod";
import { format } from "prettier";

import {
  blogFrontmatterDate,
  createBlogFrontmatterSchema,
} from "../src/content/blog-schema.ts";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const schemaPath = join(repoRoot, "schemas", "blog-frontmatter.schema.json");

const frontmatterSchema = createBlogFrontmatterSchema({
  date: blogFrontmatterDate,
  image: () =>
    z
      .string()
      .min(1)
      .describe("Local relative path or supported remote HTTPS image."),
});

const { $schema, ...jsonSchema } = z.toJSONSchema(frontmatterSchema, {
  io: "input",
});
const output = {
  $schema,
  $id: "https://jimeh.me/schemas/blog-frontmatter.schema.json",
  title: "jimeh.me Blog Frontmatter",
  description: "Frontmatter schema for posts in src/content/blog.",
  $comment:
    "Generated by scripts/generate-blog-frontmatter-schema.ts; do not edit.",
  ...jsonSchema,
};

mkdirSync(dirname(schemaPath), { recursive: true });
writeFileSync(
  schemaPath,
  await format(JSON.stringify(output, null, 2), { parser: "json" }),
);
